# Generated by Django 2.2.4 on 2019-08-14 07:01

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190814_0529'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('expert', 'Expert'), ('full_expert', 'Full expert'), ('admin', 'Admin')], default='Expert', max_length=20),
        ),
    ]
