# Generated by Django 2.2.4 on 2019-08-14 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_profiles', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('tagging_method', models.CharField(choices=[('singleMode', 'singleMode'), ('batchMode', 'batchMode')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_multi_content', models.BooleanField(default=False)),
                ('is_tagged', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserOutput',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('process_id', models.IntegerField()),
                ('profile_id', models.IntegerField()),
                ('tag_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePackage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('has_next', models.BooleanField(default=False)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Process')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='packageProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ProfilePackage'),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('text', 'text'), ('image', 'image'), ('video', 'video')], max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profile')),
            ],
        ),
    ]
