# Generated by Django 2.2.4 on 2019-08-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('blocked', 'blocked'), ('tagged', 'tagged')], default='available', max_length=20),
        ),
    ]
