# Generated by Django 2.0.13 on 2019-10-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useroutput',
            name='user',
        ),
    ]
