# Generated by Django 2.2.4 on 2019-08-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190814_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='is_blocked',
        ),
    ]
