# Generated by Django 2.2.4 on 2019-08-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190814_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[(1, 'available'), (2, 'blocked'), (3, 'tagged')], default=1, max_length=20),
        ),
    ]
