# Generated by Django 2.0.13 on 2019-10-31 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191031_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
    ]
