# Generated by Django 2.0.13 on 2019-11-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191102_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='profiles',
            new_name='profile',
        ),
    ]
