# Generated by Django 2.2.4 on 2019-08-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190817_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepackage',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='profilepackage',
            name='status',
        ),
        migrations.AddField(
            model_name='profile',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('blocked', 'blocked'), ('tagged', 'tagged')], default='available', max_length=20),
        ),
    ]
