# Generated by Django 2.2.4 on 2019-08-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190817_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_valid',
        ),
    ]
