# Generated by Django 2.2.4 on 2019-08-21 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_profile_is_valid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_tagged',
            new_name='is_valid',
        ),
    ]
