# Generated by Django 2.2.4 on 2019-08-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190821_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_tagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('blocked', 'blocked')], default='available', max_length=20),
        ),
    ]
