# Generated by Django 2.2.4 on 2019-08-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190821_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_tagged',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_valid',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.AddField(
            model_name='profilepackage',
            name='expire_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilepackage',
            name='is_tagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilepackage',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilepackage',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('blocked', 'blocked')], default='available', max_length=20),
        ),
    ]
