# Generated by Django 2.2.4 on 2019-08-24 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190824_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useroutput',
            name='tag_title',
        ),
        migrations.AddField(
            model_name='useroutput',
            name='profile_package_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OutputTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_title', models.CharField(max_length=100)),
                ('user_output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserOutput')),
            ],
        ),
    ]
