# Generated by Django 2.2.4 on 2019-08-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190824_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroutput',
            name='process_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useroutput',
            name='profile_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useroutput',
            name='profile_package_id',
            field=models.IntegerField(default=0),
        ),
    ]
