# Generated by Django 2.2.4 on 2019-08-26 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190824_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputtag',
            name='user_output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.UserOutput'),
        ),
    ]
