# Generated by Django 2.2.4 on 2019-09-08 06:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190908_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
