# Generated by Django 2.2.4 on 2019-10-23 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0021_auto_20190908_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='tagging_method',
            new_name='tag_method',
        ),
        migrations.RemoveField(
            model_name='process',
            name='details',
        ),
        migrations.RemoveField(
            model_name='process',
            name='number_of_profiles',
        ),
        migrations.RemoveField(
            model_name='process',
            name='users',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='packageProfile',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='percent',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='users',
        ),
        migrations.RemoveField(
            model_name='useroutput',
            name='profile_package_id',
        ),
        migrations.AddField(
            model_name='process',
            name='is_tagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='process',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('blocked', 'blocked')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='process',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Process'),
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='outputtag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='process',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='useroutput',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='useroutput',
            name='process_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='useroutput',
            name='profile_id',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='ProfilePackage',
        ),
    ]
