# Generated by Django 2.2.4 on 2019-10-23 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20191023_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='process',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Process'),
        ),
    ]
