# Generated by Django 2.2.4 on 2019-10-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_profile_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroutput',
            name='process_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='useroutput',
            name='profile_id',
            field=models.IntegerField(default=None),
        ),
    ]
