# Generated by Django 2.2.4 on 2019-10-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20191023_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroutput',
            name='process_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useroutput',
            name='profile_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
