# Generated by Django 2.2.4 on 2019-10-23 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20191023_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useroutput',
            name='process_id',
        ),
        migrations.RemoveField(
            model_name='useroutput',
            name='profile_id',
        ),
    ]
