# Generated by Django 2.2.4 on 2019-10-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20191023_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroutput',
            name='process_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useroutput',
            name='profile_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
