# Generated by Django 2.2.4 on 2019-10-23 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20191023_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outputtag',
            old_name='tag_title',
            new_name='title',
        ),
    ]
